# ChestなどのContaierを許可するか否か
# values:
# - allow
# - deny
container = "deny"
entity = "deny"

[blacklist]

# Blacklistとに追加するブロックを追加
# example
# - "minecraft:bedrock"
# - "minecraft:command_block"
blocks = [
  # Blocks here
  # "minecraft:command_block"
  "minecraft:polished_basalt",
  "minecraft:soul_lantern",
  "minecraft:polished_deepslate_wall",
  "minecraft:chest"
]
